"""
Default metric definitions for seeding.
Each entry defines a metric for a specific data source (by slug).
"""

DEFAULT_METRICS = [
    # ---- new_users_daily ----
    {
        "data_source_slug": "new_users_daily",
        "key": "new_users",
        "name_ru": "Новые пользователи",
        "name_en": "New Users",
        "description_ru": "Количество новых зарегистрированных пользователей за период",
        "unit": "users",
        "data_type": "integer",
        "aggregation": "sum",
        "format_pattern": "{value}",
        "is_visible": True,
        "sort_order": 0,
    },
    # ---- new_payments_daily ----
    {
        "data_source_slug": "new_payments_daily",
        "key": "total_payments_count",
        "name_ru": "Всего платежей",
        "name_en": "Total Payments",
        "description_ru": "Общее количество платежей за период",
        "unit": "count",
        "data_type": "integer",
        "aggregation": "sum",
        "format_pattern": "{value}",
        "is_visible": True,
        "sort_order": 0,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "payments_afterjoin_count",
        "name_ru": "Платежи после регистрации",
        "name_en": "Payments After Join",
        "description_ru": "Платежи от пользователей после первичной регистрации",
        "unit": "count",
        "data_type": "integer",
        "aggregation": "sum",
        "format_pattern": "{value}",
        "is_visible": True,
        "sort_order": 1,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "payments_byguest_count",
        "name_ru": "Платежи гостей",
        "name_en": "Guest Payments",
        "description_ru": "Платежи от незарегистрированных пользователей",
        "unit": "count",
        "data_type": "integer",
        "aggregation": "sum",
        "format_pattern": "{value}",
        "is_visible": True,
        "sort_order": 2,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "discounts_count",
        "name_ru": "Платежи со скидкой",
        "name_en": "Discounted Payments",
        "unit": "count",
        "data_type": "integer",
        "aggregation": "sum",
        "is_visible": True,
        "sort_order": 3,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "total_amount_gross",
        "name_ru": "Сумма (брутто)",
        "name_en": "Total Gross Amount",
        "description_ru": "Общая сумма платежей до вычета комиссий",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "sum",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 4,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "total_amount_net",
        "name_ru": "Сумма (нетто)",
        "name_en": "Total Net Amount",
        "description_ru": "Общая сумма платежей после вычета комиссий",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "sum",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 5,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "avg_amount_gross",
        "name_ru": "Средний чек (брутто)",
        "name_en": "Avg Gross Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "avg",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 6,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "avg_amount_net",
        "name_ru": "Средний чек (нетто)",
        "name_en": "Avg Net Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "avg",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 7,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "median_amount_gross",
        "name_ru": "Медиана (брутто)",
        "name_en": "Median Gross Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "avg",
        "format_pattern": "{value} руб.",
        "is_visible": False,
        "sort_order": 8,
    },
    {
        "data_source_slug": "new_payments_daily",
        "key": "median_amount_net",
        "name_ru": "Медиана (нетто)",
        "name_en": "Median Net Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "avg",
        "format_pattern": "{value} руб.",
        "is_visible": False,
        "sort_order": 9,
    },
    # ---- repeat_payments_daily ----
    {
        "data_source_slug": "repeat_payments_daily",
        "key": "total_payments_count",
        "name_ru": "Повторных платежей",
        "name_en": "Total Repeat Payments",
        "unit": "count",
        "data_type": "integer",
        "aggregation": "sum",
        "is_visible": True,
        "sort_order": 0,
    },
    {
        "data_source_slug": "repeat_payments_daily",
        "key": "total_amount_gross",
        "name_ru": "Сумма повторных (брутто)",
        "name_en": "Repeat Gross Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "sum",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 1,
    },
    {
        "data_source_slug": "repeat_payments_daily",
        "key": "total_amount_net",
        "name_ru": "Сумма повторных (нетто)",
        "name_en": "Repeat Net Amount",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "sum",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 2,
    },
    {
        "data_source_slug": "repeat_payments_daily",
        "key": "avg_amount_gross",
        "name_ru": "Средний повторный чек (брутто)",
        "name_en": "Avg Repeat Gross",
        "unit": "rub",
        "data_type": "currency",
        "aggregation": "avg",
        "format_pattern": "{value} руб.",
        "is_visible": True,
        "sort_order": 3,
    },
]
